package:
  name: test_pkg_mps
  version: 0.0.1

source:
  path: .

build:
  script: {{ PYTHON }} -m pip install . -vv 
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python 3.10
    - pip
  run:
    - python 3.10
    - pandas
    - numpy 
    - scipy
    - pyserial
    - openpyxl
    - matplotlib

about:
  home: https://github.com/your_organization/test_pkg
  summary: 'My super python package'
  description: |
    This is a test package to show how to create a conda package.
    It has a cool hello() function that prints a message.
  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  # See https://spdx.org/licenses/
  license: MIT
  # The license_family, i.e. "BSD" if license is "BSD-3-Clause". 
  # Optional
  license_family: MIT
  # It is required to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file: LICENSE
  # The doc_url and dev_url are optional.
  doc_url: https://test_pkg.readthedocs.io/
  dev_url: https://github.com/your_organization/test_pkg

